name: JKT48Live Data Update

on:
  schedule:
<<<<<<< HEAD
    - cron: "*/2 * * * *"
=======
    - cron: "*/5 * * * *"
>>>>>>> ba05aa87eb64696bc0e5b0db8e6a06fb34e8fe95
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci

      - run: mkdir -p data/idn data/showroom

      - run: node index.js
      - run: node src/generate-readme.js

      - run: git add README.md data/idn/*.json data/showroom/*.json
      - run: git pull --rebase origin main

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "update live data"
          branch: main
          commit_user_name: "github-actions"
          commit_user_email: "github-actions@github.com"