name: JKT48Live Data Update

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci

      - run: mkdir -p data/idn data/showroom

      - name: Fetch live data
        run: node index.js

      - name: Generate README
        run: node src/generate-readme.js

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "update live data"
          branch: main
          commit_user_name: "github-actions"
          commit_user_email: "github-actions@github.com"
          file_pattern: |
            README.md
            data/idn/*.json
            data/showroom/*.json
